# Generated by Django 5.2.13 on 2026-04-30 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_company_name', models.CharField(max_length=100, verbose_name='입력 회사명')),
                ('matched_company_name', models.CharField(blank=True, max_length=100, verbose_name='실제 매칭 종목명')),
                ('stock_code', models.CharField(blank=True, max_length=30, verbose_name='종목 코드')),
                ('raw_comments', models.JSONField(default=list, verbose_name='원본 댓글 목록')),
                ('cleaned_comments', models.JSONField(default=list, verbose_name='정제 댓글 목록')),
                ('augmented_comments', models.JSONField(default=list, verbose_name='증강 댓글 목록')),
                ('iqr_info', models.JSONField(blank=True, default=dict, verbose_name='IQR 임계값 정보')),
                ('summary', models.TextField(blank=True, verbose_name='댓글 요약')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
            ],
        ),
    ]
