# Generated by Django 5.2.13 on 2026-04-30 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawlingresult',
            name='inappropriate_removed_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='crawlingresult',
            name='removed_count',
            field=models.IntegerField(default=0),
        ),
    ]
