# Generated by Django 5.2.4 on 2026-04-17 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.CharField(default='익명', max_length=50),
        ),
    ]
